name: RDP-2019

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2022
    timeout-minutes: 9999
    steps:
    - name: Tải Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/em06534/test/main/Files/nssm.exe -OutFile nssm.exe
    - name: Sao chép NSSM & Ngrok đến thư mục Windows.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Kết nối đến tài khoản NGROK của bạn!
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Tải về một số thư mục quan trọng.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/em06534/test/main/Files/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://raw.githubusercontent.com/em06534/test/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/em06534/test/main/Files/loop.bat -OutFile loop.bat
    - name: Tạo tệp YML cho NGROK.
      run: start NGROK-AP.bat
    - name: Bật truy cập RDP
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tạo Tunnel
      run: sc start ngrok
    - name: Kết nối đến RDP của bạn!
      run: cmd /c NGROK-CHECK.bat
    - name: Hoàn tất! Bạn có thể đóng cửa sổ này ngay bây giờ!
      run: cmd /c loop.bat 
